### ISSUE TITLE
Updating, gimli, object and fallible-iterator

### ISSUE THREAD

**Issue by plugwash** [mstange/framehop#12]
Hi,

I am one of the Debian rust team and I am currently working on updating the backtrace crate and it's dependencies in Debian. Backtrace itself is not semver breaking but several of the crates it depends on are semver breaking. While we do have a mechanism to package multiple versions of a crate it is something we try to avoid where possible.

Therefore I have been going through the reverse dependencies of addr2line, fallible-iterator, gimli and object and preparing updates. Your crate depends on three of theese crates, gimli, object and faillible-iterator.

After bumping the dependencies I got a build failure because an enum was now marked as "non_exhaustive", causing a match statement to fail to compile because it didn't have a fallback case. After looking at the existing cases it appeared to me that returning None was the correct thing to do in the fallback case.

After preparing a patch doing that the package built successfully and tests passed.

Our patch can be found at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/5c2b008f2853a6f9382f303b71f6acaeb5e9e484/src/framehop/debian/patches/gimli-0.28-etc.patch any comments would be appreciated.

**Comment by mstange** [comment]
Thanks for the patch! I landed the updates.
