### ISSUE TITLE
Support compressed sections in the `unwinder::object` ModuleSectionInfo impl.

### ISSUE THREAD

**Issue by afranchuk** [mstange/framehop#15]
This should be fairly easy; rather than `D: From<&'data [u8]>`, there should be something like
```
enum SectionData<'data> {
    Uncompressed {
        data: &'data [u8],
        file_offset: usize,
    }
    Compressed {
        decompressed_data: Vec<u8>
    }
}
```
and `D: From<SectionData>`. The `file_offset` is for the common case where someone has `MMap`ed data and they want to "drop" the lifetime by referencing the MMap instead.

**Comment by mstange** [comment]
I think you can already do this. The user of this crate can make an enum like the one you wrote above, and then implement `Deref<Target = [u8]>` on it.

**Comment by afranchuk** [comment]
Yes, a user can do this. This is intended as a convenience (just like the rest of the `object` impl) so the user doesn't have to!
