### ISSUE TITLE
register_ordering is broken: Truncated sequence is undistingushable from sorted

### ISSUE THREAD

**Issue by ishitatsuyuki** [mstange/framehop#25]
A register ordering with the same order as `ENCODE_REGISTERS` gets encoded as 0. The decode function truncates the sequence when it sees a 0. So `[RBX, RBP, RDI, RSI, R12, R13, R14, R15]` doesn't round trip and decodes as `[]`.

We need to encode the length of the sequence, but we have no space to do so. The length can be 0 to 8. There are 40320 permutations of length 8. Multiplying this by 9 exceeds the 16-bit limit.

I'm not sure what is the best way forward. Tentatively I think we should always use the slow path when register info is needed. If rust-minidump is not walking through a large amount of stacks with common frames between them, I think it's OK to skip the cache system and always interpret the rule directly.

cc @afranchuk

**Comment by mstange** [comment]
We could limit the length to 7 instead of 8, this would free up 3 bits for the length.

**Comment by ishitatsuyuki** [comment]
Limiting the length doesn't actually do anything, there are still 40320 length 7 permutation of 8 elements. But if you are willing to sacrifice one of the non-volatile register options, then yes, I can see it work.

**Comment by mstange** [comment]
Oh, of course. @afranchuk What do you think?

**Comment by mstange** [comment]
Good point about the `Option<CacheEntry>` tag - that's certainly a lot of wasted bits. We could make the `modules_generation` a `NonZeroU16` and it would address that problem. And then we can add another `u16` into the UnwindRule, ending up with `Option<CacheEntry>` being 8-byte aligned and 8+2+(2+2+2)=16 bytes.

**Comment by afranchuk** [comment]
That would be good (and cache-friendly). In that case we could store way more registers :smiling_imp: Though obviously we already cover the callee-saved registers so that should be sufficient.

**Comment by afranchuk** [comment]
Ah yes. `u8` for that and an extra `u8` would be fine (and in theory fit the same space). Depends on the layout though...

The enum might be allowing the `Option` to have a niche value though.

**Comment by mstange** [comment]
I'm going to take a stab at fixing this.

**Comment by mstange** [comment]
Fixed in #29. `Option<CacheEntry<UnwindRuleX86_64>>` takes up 16 bytes with the fix.
