### ISSUE TITLE
Please make the  `macho-unwind-info` optional

### ISSUE THREAD

**Issue by sylvestre** [mstange/framehop#7]
Not sure it is possible but it would be nice to be able to disable macho-unwind-info
When packaging framehope for Debian, we probably don't need macho support

**Comment by mstange** [comment]
I definitely want to make it optional in this repo.

However, if the goal is to avoid the dependency in `samply`, it wouldn't achieve that goal: `macho-unwind-info` is also used by `samply-symbols`, so it would end up in `samply` anyway. The reason to have it in `samply` is to be able to symbolicate profiles on Linux where were originally captured on macOS, in the same way as on macOS. `macho-unwind-info` is used during symbolication to provide function start addresses in macOS binaries without other symbol information.
